import type { GameDef, LevelDef } from '../types';

/**
 * Function Pond drops loops entirely and asks a different question: which part
 * of this path deserves a name? Players extract a motif into a routine and then
 * compose routines out of other routines.
 */
const levels: Omit<LevelDef, 'gameId' | 'index'>[] = [
  {
    id: 'name-that-move',
    title: 'Name That Move',
    brief: 'Teach the frog one move, then use it three times.',
    lesson:
      'A function is a name for a group of instructions. Define "hop, hop, turn right" once and every call replays it — the same idea behind every function you will ever write.',
    hint: 'Build hop, hop, turn right inside your routine. Then call it three times.',
    concepts: ['functions'],
    rows: [
      'Soo',
      '~~o',
      'Goo',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight'],
    par: 6,
    routines: { max: 1, maxBlocksPerRoutine: 4, requireUse: true, suggestedNames: ['corner', 'turnTheCorner'] },
  },
  {
    id: 'the-grand-ring',
    title: 'The Grand Ring',
    brief: 'Lap the pond using one named routine.',
    lesson:
      'Every side of this ring is identical. Describe a single side inside a routine and the whole lap becomes three calls — less to write, and only one place to fix a mistake.',
    hint: 'One side is five hops and a right turn. Define that, then call it three times.',
    concepts: ['functions', 'abstraction'],
    rows: [
      'Sooooo',
      '~~~~~o',
      '~~~~~o',
      '~~~~~o',
      '~~~~~o',
      'Gooooo',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight'],
    par: 9,
    maxBlocks: 14,
    routines: { max: 1, maxBlocksPerRoutine: 6, requireUse: true, suggestedNames: ['side', 'walkOneSide'] },
  },
  {
    id: 'tight-budget',
    title: 'Tight Budget',
    brief: 'Climb six steps with only ten blocks.',
    lesson:
      'Written out, this climb takes twenty-three instructions. The budget forces the better answer: name the step, then repeat the name.',
    hint: 'One step is hop, turn left, hop, turn right. Define it and call it six times.',
    concepts: ['functions', 'abstraction'],
    rows: [
      '~~~~~~G',
      '~~~~~oo',
      '~~~~oo~',
      '~~~oo~~',
      '~~oo~~~',
      '~oo~~~~',
      'So~~~~~',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight'],
    par: 10,
    maxBlocks: 12,
    routines: { max: 1, maxBlocksPerRoutine: 4, requireUse: true, suggestedNames: ['step', 'climbOneStep'] },
  },
  {
    id: 'two-motifs',
    title: 'Two Motifs',
    brief: 'A straight dash, then a climb. Name them both.',
    lesson:
      'One routine per idea. A routine that both dashes and climbs would be useless twice over; two focused routines can be mixed in any order.',
    hint: 'Routine one: three hops. Routine two: turn left, hop, turn right, hop. Call the climb three times.',
    concepts: ['functions', 'composition'],
    rows: [
      '~~~~~~G',
      '~~~~~~o',
      '~~~~~oo',
      '~~~~oo~',
      '~~~oo~~',
      'Sooo~~~',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight'],
    par: 14,
    maxBlocks: 20,
    routines: { max: 2, maxBlocksPerRoutine: 5, requireUse: true, suggestedNames: ['dash', 'climb'] },
  },
  {
    id: 'out-and-back',
    title: 'Out and Back',
    brief: 'Raid two arms of the pond for flies, then head south.',
    lesson:
      'A well-built routine leaves the frog somewhere predictable. This one travels out, returns to the middle and turns to face the next arm, so calling it twice sweeps two arms.',
    hint: 'Out two, turn around with two left turns, back two, then one right turn to line up the next arm.',
    concepts: ['functions', 'composition', 'pathfinding'],
    rows: [
      '~~*~~',
      '~~o~~',
      '*oSo~',
      '~~o~~',
      '~~G~~',
    ],
    startDir: 0,
    palette: ['hop', 'turnLeft', 'turnRight'],
    par: 11,
    maxBlocks: 16,
    routines: { max: 1, maxBlocksPerRoutine: 8, requireUse: true, suggestedNames: ['raidArm', 'outAndBack'] },
  },
  {
    id: 'routines-all-the-way-down',
    title: 'Routines All the Way Down',
    brief: 'Eight steps, ten blocks. Routines may call routines.',
    lesson:
      'A routine is just another instruction, so routines can call each other. Wrap two steps in a "double step" and the eight-step climb needs only four calls.',
    hint: 'Define step = hop, turn left, hop, turn right. Define double = step, step. Call double four times.',
    concepts: ['functions', 'composition', 'abstraction'],
    rows: [
      '~~~~~~~~G',
      '~~~~~~~oo',
      '~~~~~~oo~',
      '~~~~~oo~~',
      '~~~~oo~~~',
      '~~~oo~~~~',
      '~~oo~~~~~',
      '~oo~~~~~~',
      'So~~~~~~~',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight'],
    par: 10,
    maxBlocks: 14,
    routines: { max: 2, maxBlocksPerRoutine: 4, requireUse: true, suggestedNames: ['step', 'doubleStep'] },
  },
  {
    id: 'the-serpentine',
    title: 'The Serpentine',
    brief: 'Catch all four flies, then finish on the golden lily.',
    lesson:
      'Real programs mix a few small routines. A lane, a right-hand turnaround and a left-hand turnaround are enough to sweep a pond of any size — and the sweep is easy to reason about, which is worth as much as being short.',
    hint: 'Sweep it like a lawnmower. Lane = four hops. Right turnaround = turn right, hop, turn right. The left turnaround mirrors it.',
    concepts: ['functions', 'composition', 'pathfinding'],
    rows: [
      'Sooo*',
      '*oooo',
      'oooo*',
      '*oooo',
      'ooooG',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight'],
    par: 19,
    maxBlocks: 26,
    routines: {
      max: 3,
      maxBlocksPerRoutine: 4,
      requireUse: true,
      suggestedNames: ['lane', 'turnRightAround', 'turnLeftAround'],
    },
  },
  {
    id: 'the-comb',
    title: 'The Comb',
    brief: 'Three prongs, three flies, one shared routine.',
    lesson:
      'Each prong is the same trip: up, eat, back, face east again. Name the trip, then name the three hops inside it — routines built from routines keep the script short.',
    hint: 'Build a three-hop routine first, then a prong routine that uses it twice.',
    concepts: ['functions', 'composition', 'abstraction'],
    rows: [
      '~*~*~*~',
      '~o~o~o~',
      '~o~o~o~',
      'SoooooG',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight'],
    par: 18,
    maxBlocks: 26,
    routines: { max: 3, maxBlocksPerRoutine: 10, requireUse: true, suggestedNames: ['three', 'prong'] },
  },
  {
    id: 'the-locked-gates',
    title: 'The Locked Gates',
    brief: 'Three identical gates stand between you and the lily.',
    lesson:
      'Patterns hide inside irregular maps. The corridor bends the same way three times — find that unit and the maze stops being a maze.',
    hint: 'Each gate is: hop, hop, turn right, hop, hop, turn left. Call it three times, then hop twice.',
    concepts: ['functions', 'pathfinding', 'obstacles'],
    rows: [
      'Soo~~~~~~',
      '~#o~~~~~~',
      '~~ooo#~~~',
      '~~~~o~~~~',
      '~~~#ooo#~',
      '~~~~~~o~~',
      '~~~~~~ooG',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight'],
    par: 11,
    maxBlocks: 18,
    routines: { max: 2, maxBlocksPerRoutine: 6, requireUse: true, suggestedNames: ['gate', 'passGate'] },
  },
  {
    id: 'the-grand-tour',
    title: 'The Grand Tour',
    brief: 'Circle the whole pond, then cut in to the centre.',
    lesson:
      'The finale: a routine for four hops, a routine that calls it twice, and a routine for a full side. Layered abstraction is how large programs stay small enough to understand.',
    hint: 'four = 4 hops. eight = four, four. side = eight, turn right. Then: side, side, side, four, turn right, four.',
    concepts: ['functions', 'composition', 'abstraction'],
    rows: [
      'Sooooooo*',
      'o~~~~~~~o',
      'o~~~~~~~o',
      'o~~~~~~~o',
      'ooooG~~~o',
      'o~~~~~~~o',
      'o~~~~~~~o',
      'o~~~~~~~o',
      '*ooooooo*',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight'],
    par: 14,
    maxBlocks: 22,
    routines: { max: 3, maxBlocksPerRoutine: 8, requireUse: true, suggestedNames: ['four', 'eight', 'side'] },
  },
];

export const functionPond: GameDef = {
  id: 'function-pond',
  title: 'Function Pond',
  tagline: 'Functions, reuse and composition',
  blurb: 'Name a move, then reuse it.',
  description:
    'No loops here — only names. Function Pond asks you to spot the repeating idea in a path, give it a name and build bigger routines out of smaller ones. It is decomposition, the skill that separates working code from maintainable code.',
  teaches: ['Functions', 'Reuse', 'Decomposition', 'Composition', 'Abstraction'],
  accent: 'violet',
  levels: levels.map((level, index) => ({ ...level, gameId: 'function-pond', index })),
};
