import type { GameDef, LevelDef } from '../types';

/**
 * Hop Quest teaches the fundamentals in order: a program is an ordered list of
 * instructions, direction is state you have to keep track of, and a loop is
 * simply a shorter way to write a repeated sequence.
 */
const levels: Omit<LevelDef, 'gameId' | 'index'>[] = [
  {
    id: 'first-hop',
    title: 'First Hop',
    brief: 'Move the frog onto the golden lily.',
    lesson:
      'A program is a list of instructions carried out in order, top to bottom. Stack three hops and the frog crosses the pond.',
    hint: 'The golden lily is three pads away. Add three hop blocks.',
    concepts: ['sequencing'],
    rows: [
      '~~~~',
      'SooG',
      '~~~~',
    ],
    startDir: 1,
    palette: ['hop'],
    par: 3,
  },
  {
    id: 'around-the-bend',
    title: 'Around the Bend',
    brief: 'Turn the frog before the lilies run out.',
    lesson:
      'The frog only ever hops the way it is facing. Turning changes its heading without moving it, so plan the turn before the hop.',
    hint: 'Hop three times to the end of the row, turn right, then hop twice more.',
    concepts: ['sequencing', 'orientation'],
    rows: [
      'Sooo',
      '~~~o',
      '~~~G',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight'],
    par: 6,
  },
  {
    id: 'the-long-way-round',
    title: 'The Long Way Round',
    brief: 'Follow the path through two corners.',
    lesson:
      'Read the whole path before you build. Every corner costs one turn block, and a turn always happens from where the frog currently faces.',
    hint: 'Two hops east, turn left, two hops north, turn right, then two hops east.',
    concepts: ['sequencing', 'orientation'],
    rows: [
      '~~ooG',
      '~~o~~',
      'Soo~~',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight'],
    par: 8,
  },
  {
    id: 'mind-the-rock',
    title: 'Mind the Rock',
    brief: 'Steer around the boulder to reach the lily.',
    lesson:
      'Rocks block a hop instead of ending the run. When the direct route is closed, route around it — the detour is part of the algorithm.',
    hint: 'Drop below the rock, cross underneath it, then climb back up to the golden lily.',
    concepts: ['orientation', 'obstacles'],
    rows: [
      '~~~~~',
      'Soo#G',
      '~~ooo',
      '~~~~~',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight'],
    par: 9,
  },
  {
    id: 'the-fly-stop',
    title: 'The Fly Stop',
    brief: 'Catch the fly, then land on the golden lily.',
    lesson:
      'Some goals have preconditions. The golden lily only counts once every fly is eaten, so the order of your steps matters.',
    hint: 'Detour north for the fly, turn all the way around, then carry on east.',
    concepts: ['sequencing', 'pathfinding'],
    rows: [
      '~~~*~',
      'Soooo',
      '~~~~G',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight'],
    par: 12,
  },
  {
    id: 'repeat-after-me',
    title: 'Repeat After Me',
    brief: 'Cross the long channel using a loop.',
    lesson:
      'Seven identical hops is seven chances to make a mistake. A loop says the same thing once and asks for it to be repeated — the first real abstraction in programming.',
    hint: 'Put a single hop inside a repeat block and set the counter to 7.',
    concepts: ['loops'],
    rows: [
      '~~~~~~~~',
      'SooooooG',
      '~~~~~~~~',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight', 'repeat'],
    par: 2,
    maxBlocks: 4,
    repeatRange: [2, 12],
  },
  {
    id: 'square-dance',
    title: 'Square Dance',
    brief: 'Ride the ring around to the golden lily.',
    lesson:
      'A loop body can hold several instructions. Four hops and a turn describe one side of a square — repeat that and you have traced the whole lap.',
    hint: 'Repeat 3 times: four hops followed by a right turn.',
    concepts: ['loops', 'orientation'],
    rows: [
      'Soooo',
      '~~~~o',
      '~~~~o',
      '~~~~o',
      'Goooo',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight', 'repeat'],
    par: 6,
    maxBlocks: 12,
    repeatRange: [2, 8],
  },
  {
    id: 'the-staircase',
    title: 'The Staircase',
    brief: 'Climb the steps to the top of the pond.',
    lesson:
      'Look for the repeating unit. Hop, turn left, hop, turn right is one step of the staircase — spot the pattern and the whole climb collapses into five blocks.',
    hint: 'Repeat 4 times: hop, turn left, hop, turn right.',
    concepts: ['loops', 'pathfinding'],
    rows: [
      '~~~~G',
      '~~~oo',
      '~~oo~',
      '~oo~~',
      'So~~~',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight', 'repeat'],
    par: 5,
    maxBlocks: 10,
    repeatRange: [2, 8],
  },
  {
    id: 'the-narrow-pass',
    title: 'The Narrow Pass',
    brief: 'Thread the channel without touching deep water.',
    lesson:
      'Not every path repeats. When a route is irregular, trace it on the board first and translate it into blocks one leg at a time.',
    hint: 'Three hops east, then alternate: down two, across two, down two, across one.',
    concepts: ['pathfinding', 'orientation'],
    rows: [
      'Soooo~~',
      '~~~o#~~',
      '~~oooo~',
      '~~o#~o~',
      '~~ooooG',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight', 'repeat'],
    par: 14,
    repeatRange: [2, 8],
  },
  {
    id: 'circuit-of-flies',
    title: 'Circuit of Flies',
    brief: 'Eat all three flies on one lap of the ring.',
    lesson:
      'Loops nest. The inner loop walks one side of the ring, the outer loop repeats the side-and-turn — two counters describing a full circuit in four blocks.',
    hint: 'Repeat 3 times: (repeat 4 times: hop) then turn right.',
    concepts: ['nested-loops', 'loops'],
    rows: [
      'Sooo*',
      'o~~~o',
      'o~~~o',
      'o~~~o',
      'Go*o*',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight', 'repeat'],
    par: 4,
    maxBlocks: 10,
    repeatRange: [2, 8],
  },
  {
    id: 'the-labyrinth',
    title: 'The Labyrinth',
    brief: 'Find the one safe route through the maze.',
    lesson:
      'Debugging beats guessing. Run a few blocks, watch where the frog stops, then extend the script from there — that is exactly how programmers work through an unfamiliar problem.',
    hint: 'Solve it in stages. Get the frog to the middle of the maze first, then plan the second half from there.',
    concepts: ['pathfinding', 'obstacles'],
    rows: [
      'o~ooooG',
      'o~~~o~o',
      'ooooo~o',
      '~~~~~~o',
      'ooo~ooo',
      'o#o#o#~',
      'S~ooooo',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight', 'repeat'],
    par: 25,
    repeatRange: [2, 8],
  },
  {
    id: 'deep-water',
    title: 'Deep Water',
    brief: 'The full maze. Every wrong hop is a splash.',
    lesson:
      'The final test: a long path, no repeating pattern to lean on, and loops available wherever a straight run appears. Plan, run, correct, repeat.',
    hint: 'Trace the route with your finger first. Wherever you count three or more hops in a line, a repeat block will save you space.',
    concepts: ['pathfinding', 'obstacles', 'loops'],
    rows: [
      'o~ooooooG',
      'o~~~o~~~o',
      'ooooo~ooo',
      '~~~~~~o~~',
      'ooo~ooo~o',
      'o~~~o~~~o',
      'ooo~ooooo',
      'o~o~~~~~o',
      'S~ooooooo',
    ],
    startDir: 1,
    palette: ['hop', 'turnLeft', 'turnRight', 'repeat'],
    par: 41,
    repeatRange: [2, 12],
  },
];

export const hopQuest: GameDef = {
  id: 'hop-quest',
  title: 'Hop Quest',
  tagline: 'Sequencing, direction and loops',
  blurb: 'Instructions in order, then loops.',
  description:
    'Guide the frog across the pond one instruction at a time. Hop Quest builds the instincts every programmer relies on: order matters, state has to be tracked, and anything you repeat can be written once.',
  teaches: ['Sequencing', 'Direction & state', 'Obstacles', 'Loops', 'Nested loops'],
  accent: 'mint',
  levels: levels.map((level, index) => ({ ...level, gameId: 'hop-quest', index })),
};
